### ISSUE TITLE
[Feature Request] Dropdown to change climate HVAC modes without turning on the primary zone or group

### ISSUE THREAD

**Issue by Zanuuu** [Noltari/aioairzone-cloud#6]
Hi @Noltari,

It's me again.
I've seen many posts/issues about HVAC mode, primary and basic zones, and I’d like to submit a simple idea.

First, I want to show you that I’ve already tried different workarounds for this issue with my limited skills. I created a script that saves the state of the primary zone, changes the mode on it, and then turns it off again if it was off before the change. It works better with the local integration due to latency issues (even with added delays and logic retries).  
The script is executable via one button per mode in Lovelace, with the mode passed as an input variable. While this workaround functions, it’s not very clean.

To improve this, I’d like to ask if it would be possible to add a workaround as a new feature :
**A dropdown list populated with 'mode_available' to control 'mode'** on group's device and/or primary zone's device

**Mode parameter** [Documentation](https://developers.airzonecloud.com/docs/web-api/#put-/installations/-installationId-)
- Example:
```bash
curl -X PUT "https://m.airzonecloud.com/api/v1/installations/{installationId}" \
 -H "accept: application/json" \
 -H "authorization: Bearer {token}" \
 -H "content-type: application/json" \
 -d '{"params":{"mode":2}}' 
```

I’m aware that various topics have been opened on this issue, but I wanted to submit this idea regardless, as it seems that modifications to the Climate card in Home Assistant may not be arriving anytime soon.

Thanks again.  
Best regards,

**Comment by Noltari** [comment]
PRs created for the Cloud integration:
- https://github.com/home-assistant/core/pull/125918
- https://github.com/home-assistant/core/pull/125917
